#ifndef CLIENT_DEVICE_TYPE_H_
#define CLIENT_DEVICE_TYPE_H_

enum ClientDeviceType
{
    CLIENT_DEVICE_TYPE_UNKNOWN = 0,
    CLIENT_DEVICE_TYPE_IOS = 1,
    CLIENT_DEVICE_TYPE_ANDROID = 2
};

#endif // CLIENT_DEVICE_TYPE_H_
